name: scheduler
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  intl: ^0.13.0
  dson: ^0.3.4

dev_dependencies:
  test: ^0.12.15+1
  http: ^0.11.3+9
  html: ^0.12.2

analyzer:
  strong-mode: true