name: scheduler
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  intl: ^0.15.0
  scheduler_base:
    git: https://github.com/denniskaselow/scheduler_base.git

dev_dependencies:
  test: ^1.5.0
  http: ^0.12.0
  html: ^0.13.0