name: nov
description: An absolute bare-bones web app.
version: 0.0.1-dev
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  vue: ^0.4.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.0
