name: scheduler_angular2
version: 0.0.1
dependencies:
  angular2: ^2.0.0-beta.17
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  scheduler:
    path: ../scheduler
  reflectable: any
transformers:
- dart_to_js_script_rewriter
- angular2:
    platform_directives: 'package:angular2/src/common/directives.dart#CORE_DIRECTIVES'
    entry_points: web/main.dart
    resolved_identifiers:
      'RbtvSchedulerService': 'package:scheduler/scheduler.dart'
- reflectable:
    entry_points: web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives

analyzer:
  strong-mode: true