name: scheduler_angular2
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  angular: ^6.0.1
  scheduler:
    path: ../scheduler

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.16.0

dependency_overrides:
  intl: ^0.16.0