name: scheduler_angular2
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^0.1.0
  scheduler:
    path: ../scheduler
  reflectable: any
transformers:
- dart_to_js_script_rewriter
- angular2:
    entry_points: web/main.dart
- reflectable:
    entry_points: web/main.dart