name: 'scheduler_react'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  react: ^1.1.1
  w_flux: ^2.3.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  scheduler:
    path: ../scheduler
  reflectable: any

transformers:
- dart_to_js_script_rewriter
- reflectable:
    entry_points: web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives

analyzer:
  strong-mode: true